#ifndef GAME_TERMS_H
#define GAME_TERMS_H

#include "game_config.h"

typedef enum GameTextId {
    TEXT_INVALID,
    TEXT_GAME_TITLE,
    TEXT_TITLE_LANGUAGE_TOGGLE,
    TEXT_DEBUG_TITLE,
    TEXT_DEBUG_ACTION_CAP,
    TEXT_DEBUG_CONTROLS,
    TEXT_DEBUG_AI_PROFILE,
    TEXT_DEBUG_AI_MEMORY,
    TEXT_DEBUG_AI_OBSERVATION,
    TEXT_AI_PROFILE_AGGRESSIVE,
    TEXT_AI_PROFILE_COUNTER,
    TEXT_AI_PROFILE_RAGE,
    TEXT_AI_PROFILE_SURVIVAL,
    TEXT_AI_PROFILE_OPPORTUNIST,
    TEXT_AI_PROFILE_TRICKSTER,

    TEXT_MENU_START_GAME,
    TEXT_MENU_RULES,
    TEXT_MENU_SETTINGS,
    TEXT_MENU_CREDITS,
    TEXT_MENU_BACK,

    TEXT_SETTINGS_TITLE,
    TEXT_SETTINGS_LANGUAGE,
    TEXT_SETTINGS_AUDIO,
    TEXT_SETTINGS_LANGUAGE_ZH_CN,
    TEXT_SETTINGS_LANGUAGE_EN,
    TEXT_SETTINGS_AUDIO_ON,
    TEXT_SETTINGS_AUDIO_OFF,

    TEXT_CAT_ORANGE,
    TEXT_CAT_TABBY,
    TEXT_CAT_MAODIE,
    TEXT_CAT_CHOUJU,
    TEXT_CAT_BANANA,

    TEXT_ACTION_HISS,
    TEXT_ACTION_SCRATCH,
    TEXT_ACTION_LAOWU_YOWL,
    TEXT_ACTION_CHEW_GUM,

    TEXT_BUFF_STRONG,
    TEXT_BUFF_FIERCE,
    TEXT_BUFF_AGILE,
    TEXT_BUFF_LOUD_VOICE,
    TEXT_BUFF_GUM_EXPERT,
    TEXT_BUFF_DODGE,
    TEXT_BUFF_DANGER_SENSE,
    TEXT_BUFF_RAGE_CAPACITY,

    TEXT_BOSS_FERAL_CLAW,
    TEXT_BOSS_IRON_WALL,
    TEXT_BOSS_RAGE_HOWL,
    TEXT_BOSS_COUNTER,
    TEXT_BOSS_DODGE,
    TEXT_BOSS_GUM_CHEWER,
    TEXT_BOSS_PROPHET,
    TEXT_BOSS_HYBRID,

    TEXT_STATUS_HP,
    TEXT_STATUS_RAGE,
    TEXT_STATUS_COOLDOWN,
    TEXT_STATUS_STUNNED,
    TEXT_STATUS_PAUSED,
    TEXT_STATUS_VICTORY,
    TEXT_STATUS_DEFEAT,
    TEXT_STATUS_DODGED,
    TEXT_STATUS_COUNTERED,
    TEXT_STATUS_WARNING,

    TEXT_RULES_TITLE,
    TEXT_RULES_SCRATCH,
    TEXT_RULES_HISS,
    TEXT_RULES_YOWL,
    TEXT_RULES_GUM,
    TEXT_TUTORIAL_INPUT,
    TEXT_TUTORIAL_PAUSE,

    TEXT_PREBATTLE_TITLE,
    TEXT_PREBATTLE_CRISIS,
    TEXT_PREBATTLE_ENEMY,
    TEXT_PREBATTLE_MODIFIERS,
    TEXT_PREBATTLE_START,

    TEXT_ERROR_SAVE_FAILED,
    TEXT_ERROR_SAVE_CORRUPT,
    TEXT_ERROR_AUDIO_MUTED,

    TEXT_CREDITS_TITLE,
    TEXT_CREDITS_GAME,
    TEXT_CREDITS_THANKS,

    TEXT_COUNT
} GameTextId;

#define TEXT_CAT_NAME(cat_id) ((GameTextId)(TEXT_CAT_ORANGE + (cat_id)))

#endif
